### ISSUE TITLE
Vervang de options met staat specifieke args.

### ISSUE THREAD

**Issue by NielsOverkamp** [NielsOverkamp/keezen#5]

**Comment by ard66** [comment]
Kaarten hoeven niet meegegeven worden. Miscchien later wel als de game weet welke kaarten je nog kunt spelen. 
Nog beschikbare kleuren meegeven is wel handig.

**Comment by ard66** [comment]
In plaats van de player.state met allerlei properties uit te breiden zijn deze op de player zelf gezet. De player.state is nu alleen nog maar de state code.

Zo kunnen de te kiezen kleuren afgeleid worden van player.others, een list met de color en name van de andere players.

De player zelf is eigenlijk de state geworden
