### ISSUE TITLE
Voeg kaart aan state.args toe in SWAP_CARD_PARTNER staat

### ISSUE THREAD

**Issue by NielsOverkamp** [NielsOverkamp/keezen#6]
Net zoals bij bijv. PLAYING_CARD

**Comment by ard66** [comment]
In plaats van de player.state met allerlei properties uit te breiden zijn deze op de player zelf gezet. De player.state is nu alleen nog maar de state code. 

Zo kunnen de te kiezen kleuren afgeleid worden van player.others, een list met de color en name van de andere players.

**Comment by NielsOverkamp** [comment]
Dus dit kan gesloten worden?

**Comment by ard66** [comment]
Wat mij betreft wel. De state zegt PLAY_CARD, de options zeggen welke kaarten gespeeld kunnen worden. Als dat voor jou voldoende is, dan mag het issue dicht.
